<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21480" started-at="2020-02-16T17:59:59Z" finished-at="2020-02-16T18:00:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21480" started-at="2020-02-16T17:59:59Z" finished-at="2020-02-16T18:00:20Z">
      <class name="TestCases.ClickOnSignUpTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="setUp" is-config="true" duration-ms="10" started-at="2020-02-16T17:59:59Z" finished-at="2020-02-16T17:59:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testOpenApplication()[pri:0, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="testOpenApplication" is-config="true" duration-ms="21221" started-at="2020-02-16T17:59:59Z" finished-at="2020-02-16T18:00:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOpenApplication -->
        <test-method status="FAIL" signature="testClinkOnLink(java.lang.reflect.Method)[pri:0, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="testClinkOnLink" duration-ms="191" started-at="2020-02-16T18:00:20Z" description="Testing clicked on Link or not." finished-at="2020-02-16T18:00:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.ClickOnSignUpTest.testClinkOnLink(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at ObjectRepoReader.ObjectMap.getObjectLocator(ObjectMap.java:40)
at TestBases.TestCasesBase.getWebElement(TestCasesBase.java:67)
at TestPages.BankHomePage.clickOnLink(BankHomePage.java:30)
at TestCases.ClickOnSignUpTest.testClinkOnLink(ClickOnSignUpTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClinkOnLink -->
        <test-method status="FAIL" signature="testFailedScenarios(java.lang.reflect.Method)[pri:1, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="testFailedScenarios" duration-ms="9" started-at="2020-02-16T18:00:20Z" description="Test filed test cases " finished-at="2020-02-16T18:00:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.ClickOnSignUpTest.testFailedScenarios(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at TestCases.ClickOnSignUpTest.testFailedScenarios(ClickOnSignUpTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailedScenarios -->
        <test-method status="FAIL" signature="testAcualExpected(java.lang.reflect.Method)[pri:2, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="testAcualExpected" duration-ms="3" started-at="2020-02-16T18:00:20Z" description="Test actual expected" finished-at="2020-02-16T18:00:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.ClickOnSignUpTest.testAcualExpected(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [That] but found [This]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [That] but found [This]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at TestCases.ClickOnSignUpTest.testAcualExpected(ClickOnSignUpTest.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAcualExpected -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="closeDriver" is-config="true" duration-ms="1" started-at="2020-02-16T18:00:20Z" finished-at="2020-02-16T18:00:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.ClickOnSignUpTest@72057ecf]" name="tearDown" is-config="true" duration-ms="632" started-at="2020-02-16T18:00:20Z" finished-at="2020-02-16T18:00:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.ClickOnSignUpTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
